### ISSUE TITLE
Extension Wish

### ISSUE THREAD

**Issue by RainerGa** [creativeIKEP/VirtualBackgroundCamera#2]
Hello,

thank you for your greate solution! 

could you extend your software with commandline parameters for
- use Default camera
- set an default solution
- start automatically
- use Defaultpicture or give the Users all Pictures in an Folder as dropdown selection
- set Default "Output Selection" and/or hide this section

With kind regards
Rainer

**Comment by creativeIKEP** [comment]
@RainerGa 

Hello.
This software is not supported running with commandline parameters (just like `VirtualBackgroundCamera.exe --hoge 1`) now.
However, you can extend with commandline parameters because this software source code is open and there is a [method for getting commandline parameters](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=net-5.0).
I may be support running with commandline parameters in the future upon request.

**Comment by RainerGa** [comment]
@creativeIKEP 

Hello,
thank you for your fast answer. I am a Java programmer. I fork your project and tryed to implement it myself but sorry for my question, but where is the main method to implement the commandline parameters (I hope you does not laugh to loud ;-). 

Can you guide me to the right file, than I would (I hope) implement the parameters myself and give the code back to your project. 

With kind regards
Rainer
